@startuml "Sequence Diagram for help us sign up"
title "Sequence Diagram for help us sign up"
footer Page %page% of %lastpage%

autonumber
autoactivate on

actor User as user

participant "help us App" as help_us_app

participant "Directus Headless CMS" as api_directus

database "User: Database" as db_user

user -> help_us_app : user selects if they are a charity or a donor

return OK

user -> help_us_app : user enters their information

help_us_app -> api_directus : users information is sent to the api

api_directus -> db_user : user information is stored in the database

return OK

return OK

return OK

@enduml