@startuml "Help us Class Diagram"
title "Help us Class Diagram"

class ExternalApiCredentials {
    + directus_api_url : str
    + directus_api_key : str
    + square_api_url : str
    + ebay_search_endpoint : str
}

class SerpService {
    - external_api_credentials : ExternalApiCredentials
    + List<SearchResult> search_with_ebay(str keyword)
}

class PaymentService {
    - external_api_credentials : ExternalApiCredentials
    + charge_with_square(List<SearchResult> search_results) : str
}

class BackendService {
    - external_api_credentials : ExternalApiCredentials
    + save_payment_result(List<SearchResult> search_results)   -
}

class SearchResult {
    + title : str
    + link : str
    + condition : str
    + price : str
    + shipping : str
    + extensions : List<str>
    + thumbnail : str

}

class SearchController {
    - serp_service : SerpService
    + search_with_ebay(str keyword) : List<SearchResult>
}

class PaymentController {
    - payment_service : PaymentService
    + pay_with_square(List<SearchResult> search_results) : str
}

class LambdaHandler {
    + handle(event, context) : dict
}


SearchController ..> SerpService : Uses

PaymentController ..> PaymentService : Uses

PaymentController ..> BackendService : Uses

LambdaHandler ..> PaymentController : Uses

LambdaHandler ..> SearchController : Uses

@enduml

