@startuml "Sequence Diagram for help us (CHARITY)"
title "Sequence Diagram for help us (CHARITY)"
footer Page %page% of %lastpage%

autonumber
autoactivate on

actor Charity as charity

participant "help us App" as help_us_app

participant "AWS Lambda Function" as api_lambda

participant "SERP API" as boundary_serp_api

participant "Square API" as boundary_square_api

database "Listings: Database" as db_listings

charity -> help_us_app #008037 : user searches for the items needed by the charity

help_us_app -> api_lambda #008037 : search query is sent to the lambda function

api_lambda -> boundary_serp_api #008037 : makes a call to the SERP API and returns the results from ebay

return OK

return OK

return results from the search from ebay

charity -> help_us_app : user confirms the items needed by the charity

help_us_app -> api_lambda #008037 : list of items needed by the charity is sent to the lambda function

api_lambda -> boundary_square_api : authorize with the "Square API"

return OK

api_lambda -> boundary_square_api : the list of items needed by the charity is sent to "Square API"

return OK


api_lambda -> db_listings : the list of items needed by the charity is sent to the database and the results are stored

return OK

return OK

return success or failure page

@enduml