@startuml "Sequence Diagram for help us (DONOR)"
title "Sequence Diagram for help us (DONOR)"
footer Page %page% of %lastpage%

autonumber
autoactivate on

actor Donor as donor

participant "help us web" as help_us_web

participant "AWS Lambda Function" as api_lambda

participant "Directus Headless CMS" as api_directus

participant "Square API" as boundary_square_api

database "Listings: Database" as db_listings


donor -> help_us_web : user selects the campaign and items they want to buy

help_us_web -> api_lambda : the list of items the non-profit needs and price

api_lambda -> boundary_square_api : the list of items the non-profit needs and price and makes the payment

return OK

api_lambda -> api_directus : makes callback to the directus api to update the database

return OK

return OK

return OK

@enduml